### ISSUE TITLE
Authentication_Error |2

### ISSUE THREAD

**Issue by XDarkTitan** [SrMotion/srmotion-proxy#4]
_requestedName|AzureBoard
f|1
protocol|146
game_version|3.71
fz|11308880
lmode|0
cbits|0
player_age|18
GDPR|1
category|_-5100hash2|-1599564001
meta|ni.com
fhash|-716928004
rid|01791B2405CDE8850477C66608011EED
platformID|0
deviceVersion|0
country|gb
hash|1382346415
mac|
wk|11B22750D9CCD8916727C597661BF255
zf|1596104164
[SERVER]: Spoofing login info
[CLIENT]: Tracking packet: eventType|0
eventName|102_PLAYER.AUTHENTICATION
Name|^^BolsLigma123
Authenticated|0
Authentication_error|2

[SERVER]: Game message: action|quit_

**Comment by pokzy** [comment]
same bruh

**Comment by vvTrinity** [comment]
i cant build the project bro errors are. a value type of "const wchar_t*" cannot be assigned to an entity of type "PWCHAR"

and more
